version: '3.9'

services:
  ssh1:
    image: ssh_test
    container_name: ssh_test_1
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.5
    ports:
      - "2000:22"

  ssh2:
    image: ssh_test
    container_name: ssh_test_2
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.6
    ports:
      - "2001:22"

  ssh3:
    image: ssh_test
    container_name: ssh_test_3
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.7
    ports:
      - "2002:22"

  ssh4:
    image: ssh_test
    container_name: ssh_test_4
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.8
    ports:
      - "2003:22"

  monitor-nginx:
    build:
      context: monitor_nginx
      dockerfile: monitor_nginx.Dockerfile
    container_name: monitor-nginx
    volumes:
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.4
    ports:
      - "8004:80"
    depends_on:
      - monitor-server
    restart: always

  monitor-server:
    build:
      context: monitor_serv_assemble_files
      dockerfile: monitor_serv.Dockerfile
    container_name: monitor-server
    command: uvicorn monitor_serv.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file:
      - monitor_serv_assemble_files/monitor_serv.env
    volumes:
      - ./monitor_serv/:/home/monitor-server-app/web
      - ./configs/monitor_serv/:/etc/iva_dashboard
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    ports:
      - "8003:8000"
    depends_on:
      - monitor-db
    restart: always


  monitor-db:
    image: postgres:alpine
    container_name: monitor-postgres_assemble_files
    env_file:
      - postgres_assemble_files/postgres.env
    volumes:
      - ./postgres_assemble_files/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - postgres_files:/var/lib/postgresql/data
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    ports:
      - "8002:5432"
    restart: always

  monitor-agent:
#    image: pavelbeard/monitor-agent:v1
    build:
      context: monitor_agent_assemble_files
      dockerfile: monitor_agent.Dockerfile
    command: uvicorn main:app --reload --host 2.0.96.1 --port 8000
    container_name: monitor-agent
    env_file:
      - monitor_agent_assemble_files/monitor_agent.env
    volumes:
      - ./monitor_agent/:/home/monitor-agent-app/api
      - ./monitor_agent_logs/:/home/monitor-agent-app/api/logs
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    ports:
      - "8001:8000"
    restart: always


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14

volumes:
  postgres_files:
  static_files: