version: '3.9'

services:
  monitor-db:
    image: postgres:alpine
    container_name: monitor-postgres
    env_file:
      - postgres.env
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    ports:
      - "8002:5432"
    restart: always

  monitor-server:
    build:
      context: .
      dockerfile: monitor_server.Dockerfile
    container_name: monitor-server
    env_file:
      - monitor_agent.env
    volumes:
      - ./monitor_srv/monitor_server/:/app
      - ./monitor_srv/etc:/etc/iva_dashboard
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    ports:
      - "8003:8000"
    restart: always

  monitor-agent:
    build:
      context: .
      dockerfile: monitor_agent.Dockerfile
    container_name: monitor-agent
    env_file:
      - monitor_agent.env
    volumes:
      - ./monitor_agent/:/app
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    ports:
      - "8001:8000"
    restart: always


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14