version: '3.9'

services:
  monitor-postgres:
    image: pavelbeard/monitor-postgres:v1.0
    container_name: test-monitor-postgres-v1.0
    env_file:
      - env/iva-dev.postgres.env
    networks:
      iva_dashboard_net.iva-dev:
        ipv4_address: 2.0.96.2
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server-frontend:
    build:
      context: monitor_serv_frontend
      dockerfile: iva-dev.monitor_serv_frontend.Dockerfile
    container_name: test-monitor-server-frontend-v0.2
    volumes:
      - static_files.iva-dev:/home/monitor-server-app/web
    ports:
      - "8004:80"
    networks:
      iva_dashboard_net.iva-dev:
        ipv4_address: 2.0.96.11
    restart: on-failure
    depends_on:
      - monitor-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server:
    build:
      context: .
      dockerfile: monitor_serv/iva-dev.monitor_serv.Dockerfile
    container_name: test-monitor-server-v0.1
    env_file:
      - env/iva-dev.monitor-serv.env
    entrypoint: ["python3.11", "/home/monitor-server-app/web/entrypoint.py"]
    volumes:
      - static_files.iva-dev:/home/monitor-server-app/web
    networks:
      iva_dashboard_net.iva-dev:
        ipv4_address: 2.0.96.1
    depends_on:
      - monitor-postgres
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  iva_dashboard_net.iva-dev:
    ipam:
      config:
        - subnet: 2.0.96.0/26
          gateway: 2.0.96.62

volumes:
  postgres_files.iva-dev:
  static_files.iva-dev:

