version: '3.9'

services:
  monitor-nginx:
    build:
      context: .
      dockerfile: dockerfiles/monitor_nginx.Dockerfile
    container_name: monitor-nginx
    volumes:
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.4
    ports:
      - "8004:80"
    depends_on:
      - monitor-server
    restart: always

  monitor-server:
    build:
      context: .
      dockerfile: dockerfiles/monitor_serv.Dockerfile
    container_name: monitor-server
    command: uvicorn monitor_server.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file:
      - envs/prod.monitor_serv.env
    volumes:
      - ./monitor_serv/:/home/monitor-server-app/web
      - ./configs/monitor_serv/:/etc/iva_dashboard
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    ports:
      - "8003:8000"
    depends_on:
      - monitor-db
    restart: always

  monitor-db:
    image: postgres:alpine
    container_name: monitor-postgres
    env_file:
      - envs/prod.postgres.env
    volumes:
      - ./postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - postgres_files:/var/lib/postgresql/data
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    ports:
      - "8002:5432"
    restart: always

  monitor-agent:
    build:
      context: .
      dockerfile: dockerfiles/monitor_agent.Dockerfile
    command: uvicorn main:app --reload --host 2.0.96.1 --port 8000
    container_name: monitor-agent
    env_file:
      - envs/prod.monitor_agent.env
    volumes:
      - ./monitor_agent/:/app
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    ports:
      - "8001:8000"
    restart: always


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14

volumes:
  postgres_files:
  static_files: