version: '3.9'

services:
  monitor-broker:
    image: pavelbeard/prod.monitor-broker:v1.0
    container_name: prod.monitor-broker-v1.0
    networks:
      iva_dashboard_net.prod:
        ipv4_address: 11.0.96.5
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  monitor-postgres:
    image: pavelbeard/prod.monitor-postgres:v1.0
    container_name: prod.monitor-postgres-v1.0
    env_file:
      - env/prod.monitor-postgres.env
    networks:
      iva_dashboard_net.prod:
        ipv4_address: 11.0.96.4
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server-frontend:
    image: pavelbeard/prod.monitor-server-frontend:v0.97
    container_name: prod.monitor-server-frontend-v0.97
    volumes:
      - static_files.prod:/home/monitor-server-app/web/staticfiles
    ports:
      - "8040:80"
    networks:
      iva_dashboard_net.prod:
        ipv4_address: 11.0.96.1
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  worker:
    build:
      context: monitor_serv
      dockerfile: prod.monitor_serv_celery.Dockerfile
    container_name: monitor-serv-worker-v1.0
    env_file:
      - env/prod.monitor-worker.env
    entrypoint: ["python3.11", "/home/celery-worker/entrypoint_worker.py"]
    networks:
      iva_dashboard_net.prod:
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

#  worker-dashboard:
#    build: ./project
#    command: flower -A core --port=5555 --broker=redis://redis:6379/0
#    ports:
#      - 5555:5555
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379/0
#    depends_on:
#      - monitor-broker
#      - worker

  monitor-server:
    build:
      context: monitor_serv
      dockerfile: prod.monitor_serv.Dockerfile
    container_name: prod.monitor-server-v0.97
    env_file:
      - env/prod.monitor-serv.env
    entrypoint: ["python3.11", "/home/monitor-server-app/web/entrypoint.py"]
    volumes:
      - static_files.prod:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net.prod:
        ipv4_address: 11.0.96.2
    depends_on:
      - monitor-postgres
      - worker
      - monitor-broker
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  iva_dashboard_net.prod:
    ipam:
      config:
        - subnet: 11.0.96.0/26
          gateway: 11.0.96.62

volumes:
  postgres_files.prod:
  static_files.prod:

