version: '3.9'

services:
  monitor-nginx:
    image: pavelbeard/monitor-nginx:v1.0
    container_name: monitor-nginx
    volumes:
      - static-files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.4
    ports:
      - "8004:80"
    depends_on:
      - monitor-server
    restart: always

  monitor-server:
    build:
      context: monitor_serv_assemble_files
      dockerfile:
    container_name: monitor-server
    env_file:
      - monitor_serv_assemble_files/prod.monitor_serv.env
    volumes:
      - ./monitor_serv/:/home/monitor-server-app/web
      - ./configs/monitor_serv/:/etc/iva_dashboard
      - static-files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    depends_on:
      - monitor-db
    restart: always

  monitor-db:
    image: pavelbeard/monitor-postgres:v1.0
    env_file:
      - postgres_assemble_files/prod.postgres.env
    volumes:
      - ./postgres_assemble_files/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - postgres-files:/var/lib/postgresql/data
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    restart: always

  monitor-agent:
    image: pavelbeard/monitor-agent:v1.2
    command: uvicorn main:app --reload --host 2.0.96.1 --port 8000
    container_name: monitor-agent
    env_file:
      - monitor_agent_assemble_files/prod.monitor_agent.env
    volumes:
      - ./monitor_agent/:/app
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    restart: always


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14

volumes:
  postgres-files:
  static-files: