version: '3.9'

services:

  monitor-nginx:
    image: pavelbeard/monitor-nginx:v1.0
    container_name: monitor-nginx
    volumes:
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 10.0.96.4
    ports:
      - "8004:80"
    depends_on:
      - monitor-server
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server:
    image: pavelbeard/monitor-server:v1.8
    container_name: monitor-server
    env_file:
      - env/prod.monitor-serv.env
    entrypoint: ["python3.11", "/home/monitor-server-app/web/entrypoint.py"]
    volumes:
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 10.0.96.3
    depends_on:
      - monitor-postgres
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  monitor-postgres:
    image: pavelbeard/monitor-postgres:v1.0
    container_name: monitor-postgres
    env_file:
      - env/prod.monitor-postgres.env
    networks:
      iva_dashboard_net:
        ipv4_address: 10.0.96.2
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-agent:
    image: pavelbeard/monitor-agent:v1.9
    container_name: monitor-agent
    env_file:
      - env/prod.monitor-agent.env
    entrypoint: ["python3.11", "/home/monitor-agent-app/monitor_agent/entrypoint.py"]
    networks:
      iva_dashboard_net:
        ipv4_address: 10.0.96.1
    depends_on:
      - monitor-server
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 10.0.96.0/28
          gateway: 10.0.96.14

volumes:
  postgres_files:
  static_files:

