version: '3.9'

services:
  monitor-nginx:
    build:
      context: monitor_nginx_assemble_files
      dockerfile: prod.monitor_nginx.Dockerfile
    container_name: monitor-nginx
    volumes:
      - static-files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.4
    ports:
      - "8004:80"
    restart: always

  monitor-server:
    build:
      context: monitor_serv
      dockerfile: prod.monitor_serv.Dockerfile
    container_name: monitor-server
    env_file:
      - monitor_serv/monitor_serv_assemble_files/prod.monitor-serv.env
    volumes:
      - ./monitor_serv/:/home/monitor-server-app/web
      - ./configs/monitor_serv/:/etc/iva_dashboard
      - static-files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    depends_on:
      - monitor-postgres
      - monitor-nginx
    restart: always

  monitor-postgres:
    image: pavelbeard/monitor-postgres:v1.0
    container_name: monitor-postgres
    env_file:
      - monitor_postgres_assemble_files/prod.monitor-postgres.env
#    volumes:
      # заменить на ~/postgres-files
#      - ./postgres-files:/var/lib/postgresql/data
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    restart: always

  monitor-agent:
    image: pavelbeard/monitor-agent:v1.2
    command: uvicorn main:app --reload --host 2.0.96.1 --port 8000
    container_name: monitor-agent
    env_file:
      - monitor_agent/monitor_agent_assemble_files/prod.monitor-agent.env
    volumes:
      - ./monitor_agent/:/home/monitor-agent-app/api
      - ./monitor_agent_logs/:/home/monitor-agent-app/api/logs
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    restart: always


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14

volumes:
  postgres-files:
  static-files: