version: '3.9'

services:
  monitor-nginx:
    build:
      context: .
      dockerfile: prod.monitor_nginx.Dockerfile
    container_name: monitor-nginx
    volumes:
      - static-files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.4
    ports:
      - "8004:80"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server:
    build:
      context: .
      dockerfile: prod.monitor_serv.Dockerfile
    container_name: monitor-server
    env_file:
      - env/prod.monitor-serv.env
    volumes:
      - static-files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    depends_on:
      - monitor-postgres
      - monitor-nginx
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-postgres:
    image: pavelbeard/monitor-postgres:v1.0
    container_name: monitor-postgres
    env_file:
      - env/prod.monitor-postgres.env
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-agent:
    build:
      context: .
      dockerfile: prod.monitor_agent.Dockerfile
    container_name: monitor-agent
    env_file:
      - env/prod.monitor-agent.env
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    depends_on:
      - monitor-server
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14

volumes:
  postgres-files:
  static-files: