version: '3.9'

services:
  monitor-postgres:
    image: pavelbeard/monitor-postgres:v1.0
    container_name: monitor-postgres-v1.0
    networks:
      iva_dashboard_net.prod:
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server-frontend:
    build:
      context: monitor_serv_frontend
      dockerfile: prod.monitor_serv_frontend.Dockerfile
    container_name: monitor-server-frontend-v0.1
    volumes:
      - static_files.prod:/home/monitor-server-app/web
    env_file:
      - env/prod.monitor-serv-frontend.env
    ports:
      - "8040:80"
    networks:
      iva_dashboard_net.prod:
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server:
    build:
      context: monitor_serv
      dockerfile: prod.monitor_serv.Dockerfile
    container_name: monitor-server-v0.1
    env_file:
      - env/prod.monitor-serv.env
    entrypoint: ["python3.11", "/home/monitor-server-app/web/entrypoint.py"]
    volumes:
      - static_files.prod:/home/monitor-server-app/web
    networks:
      iva_dashboard_net.prod:
    depends_on:
      - monitor-postgres
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  iva_dashboard_net.prod:
    driver: bridge

volumes:
  postgres_files.prod:
  static_files.prod:

