version: '3.9'

services:

  monitor-nginx:
    build:
      context: .
      dockerfile: test.monitor_nginx.Dockerfile
    container_name: monitor-nginx
    volumes:
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.4
    ports:
      - "8004:80"
    depends_on:
      - monitor-server
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-server:
    build:
      context: .
      dockerfile: test.monitor_serv.Dockerfile
    container_name: monitor-server
    env_file:
      - env/test.monitor-serv.env
    volumes:
      - static_files:/home/monitor-server-app/web/staticfiles
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.3
    depends_on:
      - monitor-postgres
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  monitor-postgres:
    build:
      context: .
      dockerfile: test.monitor_postgres.Dockerfile
    container_name: monitor-postgres
    env_file:
      - env/test.postgres.env
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.2
    ports:
      - "8002:5432"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  monitor-agent:
    build:
      context: .
      dockerfile: test.monitor_agent.Dockerfile
    container_name: monitor-agent
    env_file:
      - env/test.monitor_agent.env
    networks:
      iva_dashboard_net:
        ipv4_address: 2.0.96.1
    depends_on:
      - monitor-server
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


networks:
  iva_dashboard_net:
    ipam:
      config:
        - subnet: 2.0.96.0/28
          gateway: 2.0.96.14

volumes:
  postgres_files:
  static_files:

