# Generated by Django 4.1.4 on 2023-01-23 12:52

import dashboard_users.validators
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Обязательное и уникальное. Длина почты максимум 64 символа.Формат: username@example.com', max_length=64, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Обязательное поле.'}, help_text='Обязательное. Длина имени максимум 64 символа.Только с большой буквы', max_length=64, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Является ли пользователь активным?', verbose_name='ACTIVE'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Имеет ли право пользователь заходить в панель администратора?', verbose_name='STAFF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Является ли пользователь администратором?', verbose_name='ROOT'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(error_messages={'required': 'Обязательное поле.'}, help_text='Обязательное. Длина фамилии максимум 64 символа.Только с большой буквы', max_length=64, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Фамилия:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с данным именем уже существует.'}, help_text='Обязательное и уникальное. Длина имени пользователя максимум 32 символа.Только буквы, цифры и символы: @/./+/-/_', max_length=32, unique=True, validators=[dashboard_users.validators.MyASCIIUsernameValidator()], verbose_name='Имя пользоветеля'),
        ),
    ]
