# Generated by Django 4.1.4 on 2023-01-24 09:42

import dashboard_users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Обязательное и уникальное. Длина почты максимум 64 символа.Формат: username@example.com', max_length=64, unique=True, validators=[dashboard_users.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Обязательное поле.'}, help_text='Обязательное. Длина имени максимум 64 символа.Только с большой буквы', max_length=64, validators=[dashboard_users.validators.FirstLastNameValidator()], verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(error_messages={'required': 'Обязательное поле.'}, help_text='Обязательное. Длина фамилии максимум 64 символа.Только с большой буквы', max_length=64, validators=[dashboard_users.validators.FirstLastNameValidator()], verbose_name='Фамилия:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с данным именем уже существует.'}, help_text='Обязательное и уникальное. Длина имени пользователя максимум 32 символа.Только буквы, цифры и символы: [@_]', max_length=32, unique=True, validators=[dashboard_users.validators.ASCIIUsernameValidator()], verbose_name='Имя пользоветеля'),
        ),
    ]
