# Generated by Django 4.1.4 on 2023-01-24 10:44

import dashboard_users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с данным именем уже существует.'}, help_text='Обязательное и уникальное. Длина имени пользователя максимум 32 символа.Только буквы, цифры и символы: [@_]', max_length=32, unique=True, validators=[dashboard_users.validators.ASCIIUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
