# Generated by Django 4.1.4 on 2023-01-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Является ли пользователь активным?', verbose_name='ACTIVE'),
        ),
    ]
