# Generated by Django 4.1.4 on 2023-01-25 09:36

import dashboard_users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Обязательное и уникальное. Длина почты максимум 64 символа.Формат: username@example.com', max_length=64, unique=True, validators=[dashboard_users.validators.EmailValidator()], verbose_name='Email:'),
        ),
    ]
