# Generated by Django 4.1.4 on 2023-02-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.DeleteModel(
            name='StoredPassword',
        ),
    ]
