# Generated by Django 4.1.4 on 2023-02-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0007_alter_customuser_options_delete_storedpassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь инфопанели', 'verbose_name_plural': 'Пользователи инфопанели'},
        ),
    ]
