# Generated by Django 4.1.4 on 2023-03-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_interval', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='IP-адрес целевого сервера:')),
                ('port', models.SmallIntegerField(verbose_name='Порт сервера:')),
            ],
            options={
                'verbose_name': 'целевой хост',
                'verbose_name_plural': 'целевые хосты',
                'unique_together': {('address', 'port')},
            },
        ),
        migrations.CreateModel(
            name='PromQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('fk_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_target', to='dashboard.target')),
            ],
        ),
    ]
