# Generated by Django 4.1.4 on 2023-03-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_interval', models.SmallIntegerField(default=5)),
                ('address_for_check_ssl', models.TextField()),
                ('port', models.SmallIntegerField()),
                ('protocol', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='BackendSettings',
        ),
    ]
