# Generated by Django 4.1.4 on 2023-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboardsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='target',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='target',
            name='is_being_scan',
            field=models.BooleanField(default=True, verbose_name='Сервер сканируется?'),
        ),
        migrations.AddField(
            model_name='target',
            name='password',
            field=models.CharField(max_length=256, null=True, verbose_name='Пароль сервера:'),
        ),
        migrations.AddField(
            model_name='target',
            name='port_ssh',
            field=models.SmallIntegerField(default=22, verbose_name='Порт ssh:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='port',
            field=models.SmallIntegerField(default=11650, verbose_name='Порт prometheus:'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('address', 'port', 'port_ssh')},
        ),
    ]
