# Generated by Django 4.1.4 on 2022-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.UUIDField(default='160e6bccb945423bad2073fafd024b89', primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=64)),
                ('os', models.CharField(max_length=32)),
                ('kernel', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('uuid', models.UUIDField(default='9ce720f5319942bea7374f4dee13f3ee', primary_key=True, serialize=False, verbose_name='UUID записи')),
                ('address', models.GenericIPAddressField(verbose_name='IP-адрес целевого сервера')),
                ('port', models.SmallIntegerField(verbose_name='Порт сервера')),
                ('username', models.CharField(max_length=32, verbose_name='Логин сервера')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль сервера')),
            ],
        ),
    ]
