# Generated by Django 4.1.4 on 2022-12-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default='ad75b8b7f2d346648657a48b750cf5a7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='target',
            name='uuid',
            field=models.UUIDField(default='5a9f2fe62f7645d3a6ce7e33ef5abfe4', primary_key=True, serialize=False, verbose_name='UUID записи'),
        ),
    ]
