# Generated by Django 4.1.4 on 2023-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Данные сервера', 'verbose_name_plural': 'Данные сервера'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Целевой хост', 'verbose_name_plural': 'Целевые хосты'},
        ),
        migrations.AlterField(
            model_name='target',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль сервера:'),
        ),
    ]
