# Generated by Django 4.1.4 on 2023-03-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardsettings_delete_backendsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardsettings',
            options={'verbose_name': 'настройки дашборда', 'verbose_name_plural': 'настройки дашборда'},
        ),
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='refresh_interval',
        ),
        migrations.DeleteModel(
            name='PromQL',
        ),
    ]
