# Generated by Django 4.1.4 on 2023-01-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_server_options_alter_target_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
