# Generated by Django 4.1.4 on 2022-12-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_server_uuid_alter_target_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='server_role',
            field=models.CharField(choices=[('media', 'MEDIA'), ('slave', 'SLAVE'), ('master', 'MASTER')], default='media', max_length=6, verbose_name='Роль сервера'),
        ),
    ]
