# Generated by Django 4.1.4 on 2022-12-27 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_target_server_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSpace',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetInterface',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='address',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP-адрес сервера:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=64, verbose_name='Имя сервера:'),
        ),
        migrations.AlterField(
            model_name='server',
            name='kernel',
            field=models.CharField(max_length=64, verbose_name='Ядро ОС:'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(max_length=32, verbose_name='Операционная система:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес целевого сервера:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='password',
            field=models.CharField(max_length=32, verbose_name='Пароль сервера:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='port',
            field=models.SmallIntegerField(verbose_name='Порт сервера:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='server_role',
            field=models.CharField(choices=[('media', 'MEDIA'), ('head', 'HEAD')], default='media', max_length=6, verbose_name='Роль сервера:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Логин сервера:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cpu_cores', models.IntegerField(verbose_name='Количество ядер:')),
                ('cpu_load', models.FloatField(verbose_name='Загрузка процессора %:')),
                ('cpu_idle', models.FloatField(verbose_name='Простой процессора %:')),
                ('record_date', models.DateTimeField(auto_now=True, verbose_name='Информация взята:')),
                ('server_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.server', verbose_name='Сервер:')),
            ],
        ),
    ]
