# Generated by Django 4.1.4 on 2023-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_cpu_cpu_load_cpu_cpu_iowait_cpu_cpu_irq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='ram_avail',
            field=models.FloatField(default=0, verbose_name='Доступной памяти:'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_buff_cached',
            field=models.FloatField(default=0, verbose_name='Буферизованной/кэшированной памяти:'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_shared',
            field=models.FloatField(default=0, verbose_name='Общей памяти:'),
        ),
    ]
