# Generated by Django 4.1.4 on 2023-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_target_unique_together_target_is_being_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='username',
            field=models.CharField(default='admin', max_length=32),
        ),
    ]
