# Generated by Django 4.1.4 on 2023-01-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_diskspace_netinterface_ram_server_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='address',
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_free',
            field=models.FloatField(default=0, verbose_name='Свободной памяти:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_used',
            field=models.FloatField(default=0, verbose_name='Занятой памяти:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='record_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время сканирования:'),
        ),
        migrations.AddField(
            model_name='ram',
            name='server_uuid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.server', verbose_name='Сервер:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='total_ram',
            field=models.FloatField(default=0, verbose_name='Всего RAM:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='target_uuid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Целевой хост:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu',
            name='record_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время сканирования:'),
        ),
        migrations.AlterField(
            model_name='target',
            name='address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP-адрес целевого сервера:'),
        ),
    ]
