# Generated by Django 4.1.4 on 2023-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_target_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
