# Generated by Django 4.1.4 on 2023-01-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ram_ram_avail_ram_ram_buff_cached_ram_ram_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_util',
            field=models.FloatField(default=0, verbose_name='Загрузка процессора %:'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_util',
            field=models.FloatField(default=0, verbose_name='Загрузка памяти %:'),
        ),
    ]
