# Generated by Django 4.1.4 on 2023-01-31 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_cpu_cpu_util_ram_ram_util'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='hostname',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Имя сервера:'),
        ),
        migrations.AddField(
            model_name='target',
            name='kernel',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Ядро ОС:'),
        ),
        migrations.AddField(
            model_name='target',
            name='os',
            field=models.CharField(blank=True, editable=False, max_length=32, verbose_name='Операционная система:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:'),
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
