# Generated by Django 4.1.4 on 2023-01-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_server_address_ram_ram_free_ram_ram_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskspace',
            name='file_system',
            field=models.CharField(default='none', max_length=128, verbose_name='Файловая система:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='fs_avail',
            field=models.FloatField(default=0, verbose_name='Доступно:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='fs_size',
            field=models.FloatField(default=0, verbose_name='Размер файловой системы:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='fs_used',
            field=models.FloatField(default=0, verbose_name='Занято:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='fs_used_prc',
            field=models.FloatField(default=0, verbose_name='Занято в %:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='mounted_on',
            field=models.CharField(default='none', max_length=128, verbose_name='Подключено к:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='record_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время сканирования:'),
        ),
        migrations.AddField(
            model_name='diskspace',
            name='server_uuid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.server', verbose_name='Сервер:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netinterface',
            name='interface',
            field=models.CharField(default='null', max_length=32, verbose_name='Интерфейс:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP-адрес интерфейса:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='record_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время сканирования:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='rx_bytes',
            field=models.FloatField(default=0, verbose_name='Получено байтов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='rx_errors_dropped',
            field=models.FloatField(default=0, verbose_name='Отброшено пакетов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='rx_errors_frame',
            field=models.FloatField(default=0, verbose_name='Неправильных кадров:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='rx_errors_overruns',
            field=models.FloatField(default=0, verbose_name='Перерасходованных пакетов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='rx_packets',
            field=models.FloatField(default=0, verbose_name='Получено пакетов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='server_uuid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.server', verbose_name='Сервер:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netinterface',
            name='status',
            field=models.CharField(default='null', max_length=4, verbose_name='Состояние:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_bytes',
            field=models.FloatField(default=0, verbose_name='Отправлено байтов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_errors_carrier',
            field=models.FloatField(default=0, verbose_name='Пакетов с потерянными носителями :'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_errors_collisions',
            field=models.FloatField(default=0, verbose_name='Отправлено пакетов с коллизиями:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_errors_dropped',
            field=models.FloatField(default=0, verbose_name='Отброшено при отправке пакетов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_errors_errors',
            field=models.FloatField(default=0, verbose_name='Отправлено с ошибками:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_errors_overruns',
            field=models.FloatField(default=0, verbose_name='Перерасходованных при отправке пакетов:'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='tx_packets',
            field=models.FloatField(default=0, verbose_name='Отправлено пакетов:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_cores',
            field=models.IntegerField(default=0, verbose_name='Количество ядер:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_idle',
            field=models.FloatField(default=0, verbose_name='Простой процессора %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_load',
            field=models.FloatField(default=0, verbose_name='Загрузка процессора %:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_free',
            field=models.FloatField(default=0, verbose_name='Свободной памяти:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_used',
            field=models.FloatField(default=0, verbose_name='Занятой памяти:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='total_ram',
            field=models.FloatField(default=0, verbose_name='Всего RAM:'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='none', max_length=64, verbose_name='Имя сервера:'),
        ),
        migrations.AlterField(
            model_name='server',
            name='kernel',
            field=models.CharField(default='none', max_length=64, verbose_name='Ядро ОС:'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(default='none', max_length=32, verbose_name='Операционная система:'),
        ),
    ]
