# Generated by Django 4.1.4 on 2023-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_target_hostname_target_kernel_target_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netinterface',
            name='rx_errors_errors',
            field=models.IntegerField(default=0, verbose_name='Пакетов с ошибками:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_dropped',
            field=models.IntegerField(default=0, verbose_name='Отброшено пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_frame',
            field=models.IntegerField(default=0, verbose_name='Неправильных кадров:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_overruns',
            field=models.IntegerField(default=0, verbose_name='Перерасходованных пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_carrier',
            field=models.IntegerField(default=0, verbose_name='Пакетов с потерянными носителями :'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_collisions',
            field=models.IntegerField(default=0, verbose_name='Отправлено пакетов с коллизиями:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_dropped',
            field=models.IntegerField(default=0, verbose_name='Отброшено при отправке пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_errors',
            field=models.IntegerField(default=0, verbose_name='Отправлено с ошибками:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_overruns',
            field=models.IntegerField(default=0, verbose_name='Перерасходованных при отправке пакетов:'),
        ),
    ]
