# Generated by Django 4.1.4 on 2023-02-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_netinterface_rx_errors_errors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'Данные процессора', 'verbose_name_plural': 'Данные процессоров'},
        ),
        migrations.AlterModelOptions(
            name='diskspace',
            options={'verbose_name': 'Данные файлового накопителя', 'verbose_name_plural': 'Данные файловых накопителей'},
        ),
        migrations.AlterModelOptions(
            name='netinterface',
            options={'verbose_name': 'Данные сетевых интерфейсов', 'verbose_name_plural': 'Данные сетевых интерфейсов'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Данные ОЗУ', 'verbose_name_plural': 'Данные ОЗУ'},
        ),
    ]
