# Generated by Django 4.1.4 on 2023-02-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_target_hostname_remove_target_kernel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'Данные процессора', 'verbose_name_plural': '3.Данные процессоров'},
        ),
        migrations.AlterModelOptions(
            name='diskspace',
            options={'verbose_name': 'Данные файлового накопителя', 'verbose_name_plural': '5.Данные файловых накопителей'},
        ),
        migrations.AlterModelOptions(
            name='netinterface',
            options={'verbose_name': 'Данные сетевых интерфейсов', 'verbose_name_plural': '6.Данные сетевых интерфейсов'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Данные ОЗУ', 'verbose_name_plural': '4.Данные ОЗУ'},
        ),
        migrations.AlterModelOptions(
            name='serverdata',
            options={'verbose_name': 'Данные сервера', 'verbose_name_plural': '2.Данные серверов'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Целевой хост', 'verbose_name_plural': '1.Целевые хосты'},
        ),
    ]
