# Generated by Django 4.1.4 on 2023-02-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_cpu_options_alter_diskspace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя сервера:'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='kernel',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ядро ОС:'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='os',
            field=models.CharField(blank=True, max_length=32, verbose_name='Операционная система:'),
        ),
    ]
