# Generated by Django 4.1.4 on 2023-02-01 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_serverdata_hostname_alter_serverdata_kernel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:'),
        ),
    ]
