# Generated by Django 4.1.4 on 2023-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_cpu_record_date_alter_diskspace_record_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_url', models.CharField(blank=True, max_length=255, verbose_name='URL агента мониторинга')),
                ('scrape_interval', models.IntegerField(default=15, verbose_name='Интервал снятия метрик:')),
            ],
        ),
    ]
