# Generated by Django 4.1.4 on 2023-02-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_dashboardsettings_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardsettings',
            options={'verbose_name': 'Настройки сервера', 'verbose_name_plural': 'Настройки сервера'},
        ),
    ]
