# Generated by Django 4.1.4 on 2023-02-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_dashboardsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskspace',
            name='fs_avail',
            field=models.CharField(default='none', max_length=10, verbose_name='Доступно:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_size',
            field=models.CharField(default='none', max_length=10, verbose_name='Размер файловой системы:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_used',
            field=models.CharField(default='none', max_length=10, verbose_name='Занято:'),
        ),
    ]
