# Generated by Django 4.1.4 on 2023-02-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_diskspace_fs_avail_alter_diskspace_fs_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskspace',
            name='total_disk_size',
            field=models.CharField(default='none', max_length=128, verbose_name='Размер диска:'),
        ),
    ]
