# Generated by Django 4.1.4 on 2023-02-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_diskspace_total_disk_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskspace',
            name='total_disk_size',
        ),
    ]
