# Generated by Django 4.1.4 on 2023-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_diskspace_total_disk_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsettings',
            name='command_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
