# Generated by Django 4.1.4 on 2023-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_dashboardsettings_command_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_idle',
            field=models.FloatField(default=0, verbose_name='Простой процессора, id %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_iowait',
            field=models.FloatField(default=0, verbose_name='Ожидание ввода/вывода, wa %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_irq',
            field=models.FloatField(default=0, verbose_name='Запросы на прерывание, hi %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_nice',
            field=models.FloatField(default=0, verbose_name="'Приятная' загрузка процессора, ni %:"),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_softirq',
            field=models.FloatField(default=0, verbose_name='Программные прерывания, si %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_steal',
            field=models.FloatField(default=0, verbose_name='Нехватка времени в ВМ, st %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_sys',
            field=models.FloatField(default=0, verbose_name='Системное время, sy %:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_user',
            field=models.FloatField(default=0, verbose_name='Пользовательское время, us %:'),
        ),
    ]
