# Generated by Django 4.1.4 on 2023-02-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_cpu_uuid_record_alter_diskspace_uuid_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='server_id',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='diskspace',
            old_name='server_id',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='netinterface',
            old_name='server_id',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='server_id',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='serverdata',
            old_name='server_id',
            new_name='target',
        ),
    ]
