# Generated by Django 4.1.4 on 2023-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_server_id_cpu_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskspace',
            name='fs_avail',
            field=models.FloatField(default='none', max_length=10, verbose_name='Доступно:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_size',
            field=models.FloatField(default='none', max_length=10, verbose_name='Размер файловой системы:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_used',
            field=models.FloatField(default='none', max_length=10, verbose_name='Занято:'),
        ),
    ]
