# Generated by Django 4.1.4 on 2023-02-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_diskspace_fs_avail_alter_diskspace_fs_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeCommands',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('scrape_command', models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга:')),
                ('scrape_command_cpu', models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга CPU:')),
                ('scrape_command_ram', models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга RAM:')),
                ('scrape_command_fs', models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга файловой системы:')),
                ('scrape_command_net', models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга сетевых интерфейсов:')),
            ],
            options={
                'verbose_name': 'Набор команд мониторинга',
            },
        ),
        migrations.AddField(
            model_name='target',
            name='scrape_commands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.scrapecommands', verbose_name='Набор команд мониторинга:'),
        ),
    ]
