# Generated by Django 4.1.4 on 2023-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_scrapecommands_target_scrape_commands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapecommands',
            options={'verbose_name': 'Набор команд мониторинга', 'verbose_name_plural': 'Набор команд мониторинга'},
        ),
        migrations.AddField(
            model_name='scrapecommands',
            name='scrape_command_apps',
            field=models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга приложений:'),
        ),
        migrations.AddField(
            model_name='scrapecommands',
            name='scrape_command_hostnamectl',
            field=models.CharField(blank=True, max_length=128, verbose_name='Мониторинг версии ОС, ядра и имени хоста:'),
        ),
        migrations.AddField(
            model_name='scrapecommands',
            name='scrape_command_uptime',
            field=models.CharField(blank=True, max_length=128, verbose_name='Команда мониторинга времени работы:'),
        ),
        migrations.AlterField(
            model_name='scrapecommands',
            name='scrape_command',
            field=models.CharField(blank=True, max_length=512, verbose_name='Команда мониторинга:'),
        ),
    ]
