# Generated by Django 4.1.4 on 2023-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_scrapecommands_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapecommands',
            name='record_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
