# Generated by Django 4.1.4 on 2023-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_scrapecommands_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapecommands',
            name='record_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
