# Generated by Django 4.1.4 on 2023-02-07 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_scrapecommands_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapecommands',
            name='record_id',
        ),
        migrations.AddField(
            model_name='scrapecommands',
            name='uuid_record',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
