# Generated by Django 4.1.4 on 2023-02-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_rename_scrapecommands_scrapecommand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='scrape_commands',
            new_name='scrape_command',
        ),
    ]
