# Generated by Django 4.1.4 on 2023-02-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_target_scrape_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='scrape_command',
        ),
    ]
