# Generated by Django 4.1.4 on 2023-02-08 09:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_target_scrape_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netinterface',
            name='interface',
            field=models.CharField(default='none', max_length=32, verbose_name='Интерфейс:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='status',
            field=models.CharField(default='none', max_length=4, verbose_name='Состояние:'),
        ),
        migrations.CreateModel(
            name='DiskSpaceStatistics',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_disk_size', models.FloatField(default=0, verbose_name='Всего места на диске:')),
                ('most_valuable_part_fs', models.CharField(default='none', max_length=128, verbose_name="Самая 'лучший' раздел файловая система:")),
                ('most_valuable_part_size', models.IntegerField(default=0, verbose_name="Размер 'лучшего' раздела файловой системы")),
                ('most_valuable_part_used', models.IntegerField(default=0, verbose_name="Используемый размер 'лучшего' раздела файловой системы")),
                ('most_valuable_part_available', models.IntegerField(default=0, verbose_name="Доступный размер 'лучшего' раздела файловой системы")),
                ('most_valuable_part_use_percent', models.CharField(default='none', max_length=4, verbose_name="Доступный размер 'лучшего' раздела файловой системы %")),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:')),
            ],
            options={
                'verbose_name': 'Статистика файловой системы',
                'verbose_name_plural': '5.1.Статистика файловой системы',
            },
        ),
    ]
