# Generated by Django 4.1.4 on 2023-02-08 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_netinterface_interface_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'Данные процессора', 'verbose_name_plural': 'Данные процессоров'},
        ),
        migrations.AlterModelOptions(
            name='diskspace',
            options={'verbose_name': 'Данные файлового накопителя', 'verbose_name_plural': 'Данные файловых накопителей'},
        ),
        migrations.AlterModelOptions(
            name='diskspacestatistics',
            options={'verbose_name': 'Статистика файловой системы', 'verbose_name_plural': 'Статистика файловой системы'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Данные ОЗУ', 'verbose_name_plural': 'Данные ОЗУ'},
        ),
        migrations.AlterModelOptions(
            name='serverdata',
            options={'verbose_name': 'Данные сервера', 'verbose_name_plural': 'Данные серверов'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Целевой хост', 'verbose_name_plural': 'Целевые хосты'},
        ),
        migrations.CreateModel(
            name='Uptime',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uptime', models.CharField(default='none', max_length=32, verbose_name='Время работы сервера:')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:')),
            ],
            options={
                'verbose_name': 'Время работы сервера',
                'verbose_name_plural': 'Время работы серверов',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_name', models.CharField(default='none', max_length=64, verbose_name='Имя процесса:')),
                ('process_status', models.CharField(default='none', max_length=16, verbose_name='Статус:')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сканирования:')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:')),
            ],
            options={
                'verbose_name': 'Статистика файловой системы',
                'verbose_name_plural': 'Статистика файловой системы',
            },
        ),
    ]
