# Generated by Django 4.1.4 on 2023-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_rename_ram_buff_cached_ram_ram_buff_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес целевого сервера:'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('address', 'port')},
        ),
    ]
