# Generated by Django 4.1.4 on 2023-02-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_target_address_alter_target_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='scraper_url_health_check',
            field=models.CharField(blank=True, max_length=255, verbose_name='Проверка состояния агента:'),
        ),
        migrations.AlterField(
            model_name='dashboardsettings',
            name='scraper_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL агента мониторинга:'),
        ),
    ]
