# Generated by Django 4.1.4 on 2023-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_dashboardsettings_scraper_url_health_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='server_role',
        ),
        migrations.AddField(
            model_name='serverdata',
            name='server_role',
            field=models.CharField(choices=[('media', 'MEDIA'), ('head', 'HEAD')], default='media', max_length=6, verbose_name='Роль сервера:'),
        ),
    ]
