# Generated by Django 4.1.4 on 2023-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_netinterface_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_cores',
            field=models.SmallIntegerField(default=0, verbose_name='Количество ядер:'),
        ),
        migrations.AlterField(
            model_name='dashboardsettings',
            name='scrape_interval',
            field=models.SmallIntegerField(default=15, verbose_name='Интервал снятия метрик:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_avail',
            field=models.BigIntegerField(default=0, verbose_name='Доступно:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файловой системы:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='fs_used',
            field=models.BigIntegerField(default=0, verbose_name='Занято:'),
        ),
        migrations.AlterField(
            model_name='diskspacestatistics',
            name='most_valuable_part_available',
            field=models.BigIntegerField(default=0, verbose_name="Доступный размер 'лучшего' раздела файловой системы"),
        ),
        migrations.AlterField(
            model_name='diskspacestatistics',
            name='most_valuable_part_size',
            field=models.BigIntegerField(default=0, verbose_name="Размер 'лучшего' раздела файловой системы"),
        ),
        migrations.AlterField(
            model_name='diskspacestatistics',
            name='most_valuable_part_use_percent',
            field=models.FloatField(default=0, verbose_name="Доступный размер 'лучшего' раздела файловой системы %"),
        ),
        migrations.AlterField(
            model_name='diskspacestatistics',
            name='most_valuable_part_used',
            field=models.BigIntegerField(default=0, verbose_name="Используемый размер 'лучшего' раздела файловой системы"),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_bytes',
            field=models.BigIntegerField(default=0, verbose_name='Получено байтов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_dropped',
            field=models.BigIntegerField(default=0, verbose_name='Отброшено пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_errors',
            field=models.BigIntegerField(default=0, verbose_name='Пакетов с ошибками:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_frame',
            field=models.BigIntegerField(default=0, verbose_name='Неправильных кадров:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_errors_overruns',
            field=models.BigIntegerField(default=0, verbose_name='Перерасходованных пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='rx_packets',
            field=models.BigIntegerField(default=0, verbose_name='Получено пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_bytes',
            field=models.BigIntegerField(default=0, verbose_name='Отправлено байтов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_carrier',
            field=models.BigIntegerField(default=0, verbose_name='Пакетов с потерянными носителями :'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_collisions',
            field=models.BigIntegerField(default=0, verbose_name='Отправлено пакетов с коллизиями:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_dropped',
            field=models.BigIntegerField(default=0, verbose_name='Отброшено при отправке пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_errors',
            field=models.BigIntegerField(default=0, verbose_name='Отправлено с ошибками:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_errors_overruns',
            field=models.BigIntegerField(default=0, verbose_name='Перерасходованных при отправке пакетов:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='tx_packets',
            field=models.BigIntegerField(default=0, verbose_name='Отправлено пакетов:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_avail',
            field=models.BigIntegerField(default=0, verbose_name='Доступной памяти:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_buff_cache',
            field=models.BigIntegerField(default=0, verbose_name='Буферизованной/кэшированной памяти:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_free',
            field=models.BigIntegerField(default=0, verbose_name='Свободной памяти:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_shared',
            field=models.BigIntegerField(default=0, verbose_name='Общей памяти:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_used',
            field=models.BigIntegerField(default=0, verbose_name='Занятой памяти:'),
        ),
    ]
