# Generated by Django 4.1.4 on 2023-02-11 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_cpu_cpu_cores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdata',
            name='uuid_record',
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.target', verbose_name='Сервер:'),
        ),
    ]
