# Generated by Django 4.1.4 on 2023-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_remove_serverdata_uuid_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='server_role',
            field=models.CharField(blank=True, choices=[('media', 'MEDIA'), ('master', 'MASTER'), ('slave', 'SLAVE')], max_length=6, verbose_name='Роль сервера:'),
        ),
    ]
