# Generated by Django 4.1.4 on 2023-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_serverdata_server_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_apps',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга приложений:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_cpu',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга CPU:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_fs',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга файловой системы:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_hostnamectl',
            field=models.TextField(blank=True, verbose_name='Мониторинг версии ОС, ядра и имени хоста:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_net',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга сетевых интерфейсов:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_ram',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга RAM:'),
        ),
        migrations.AlterField(
            model_name='scrapecommand',
            name='scrape_command_uptime',
            field=models.TextField(blank=True, verbose_name='Команда мониторинга времени работы:'),
        ),
    ]
