# Generated by Django 4.1.4 on 2023-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_scrapecommand_scrape_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя сервера:'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='kernel',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ядро ОС:'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='os',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Операционная система:'),
        ),
    ]
