# Generated by Django 4.1.4 on 2023-02-14 11:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_serverdata_hostname_alter_serverdata_kernel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'данные процессора', 'verbose_name_plural': 'данные процессоров'},
        ),
        migrations.AlterModelOptions(
            name='dashboardsettings',
            options={'verbose_name': 'настройки сервера мониторинга', 'verbose_name_plural': 'настройки сервера мониторинга'},
        ),
        migrations.AlterModelOptions(
            name='diskspace',
            options={'verbose_name': 'данные файлового накопителя', 'verbose_name_plural': 'данные файловых накопителей'},
        ),
        migrations.AlterModelOptions(
            name='diskspacestatistics',
            options={'verbose_name': 'статистика файловой системы', 'verbose_name_plural': 'статистика файловой системы'},
        ),
        migrations.AlterModelOptions(
            name='netinterface',
            options={'verbose_name': 'данные сетевых интерфейсов', 'verbose_name_plural': 'данные сетевых интерфейсов'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'статистика файловой системы', 'verbose_name_plural': 'статистика файловой системы'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'данные ОЗУ', 'verbose_name_plural': 'данные ОЗУ'},
        ),
        migrations.AlterModelOptions(
            name='scrapecommand',
            options={'verbose_name': 'команды мониторинга', 'verbose_name_plural': 'команды мониторинга'},
        ),
        migrations.AlterModelOptions(
            name='serverdata',
            options={'verbose_name': 'данные сервера', 'verbose_name_plural': 'данные серверов'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'целевой хост', 'verbose_name_plural': 'целевые хосты'},
        ),
        migrations.AlterModelOptions(
            name='uptime',
            options={'verbose_name': 'время работы сервера', 'verbose_name_plural': 'время работы серверов'},
        ),
        migrations.AddField(
            model_name='scrapecommand',
            name='scrape_command_load_average',
            field=models.TextField(blank=True, verbose_name='Мониторинг средней загрузки хоста:'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='diskspace',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='diskspacestatistics',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='process',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='serverdata',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.AlterField(
            model_name='uptime',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
        migrations.CreateModel(
            name='LoadAverage',
            fields=[
                ('uuid_record', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('one_min', models.FloatField(default=0, verbose_name='Средняя загрузка системы за 1 минуту:')),
                ('five_min', models.FloatField(default=0, verbose_name='Средняя загрузка системы за 5 минут:')),
                ('fteen_min', models.FloatField(default=0, verbose_name='Средняя загрузка системы за 15 минут:')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.target', verbose_name='Сервер:')),
            ],
            options={
                'verbose_name': 'средняя загрузка сервера',
                'verbose_name_plural': 'средняя загрузка серверов',
            },
        ),
    ]
