# Generated by Django 4.1.4 on 2023-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_alter_target_scrape_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskspace',
            name='cluster_id',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
