# Generated by Django 4.1.4 on 2023-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_diskspace_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='netinterface',
            name='interface_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
