# Generated by Django 4.1.4 on 2023-03-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_netinterface_interface_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_apps',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_cpu',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_fs',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_hostnamectl',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_load_average',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_net',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_ram',
        ),
        migrations.RemoveField(
            model_name='scrapecommand',
            name='scrape_command_uptime',
        ),
    ]
