# Generated by Django 4.1.4 on 2023-03-07 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_remove_cpu_cpu_cores_remove_cpu_cpu_idle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='processes',
            new_name='metrics',
        ),
        migrations.RenameField(
            model_name='uptime',
            old_name='uptime',
            new_name='metrics',
        ),
        migrations.AddField(
            model_name='process',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время опроса:'),
        ),
    ]
